development:
  adapter: postgresql
  encoding: unicode
  database: sportground
  pool: 5
  host: localhost
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: sportground
  pool: 5
  username: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: unicode
  database: sportground
  pool: 5
  username: postgres
  password: postgres